### ISSUE TITLE
Lack of fee information

### ISSUE THREAD

**Issue by musicslayer** [Permissionless-Software-Foundation/bch-api#161]
I am trying to get information about a certain transaction:

https://api.fullstack.cash/v5/electrumx/tx/data/bd6e199de414844caccef1df421c7e9387f9084cb5a7e5e3922fc0a0750712a9

I get the following:

<details>
{"success":true,"details":{"blockhash":"000000000000000000ab79ad1a97b1384831dbfe6e7968975f75c5a4421f2d63","blocktime":1629428623,"confirmations":85,"hash":"bd6e199de414844caccef1df421c7e9387f9084cb5a7e5e3922fc0a0750712a9","hex":"0100000001f5a3be60e24de1b25aac5a32bca128244e0671d9f0bf94458c9aa8df09542ad1010000006a47304402203b8133fe6a0042b7491f7eb9a57107dbe575b5f88f5b907d0ad5761fde71a734022046073549710c5a71ddc63349a9814e9bf92aa16a5e8ec06d8a04ac06bc0b92204121030e5d88770c33a3ede650077c3b06461fdd56171caf86b2a23ce5cf3862bab3e1feffffff02a0860100000000001976a9148fd1c7d06d7b4adcc666856936c97eab06fafedb88ac7c0b0300000000001976a914fdf50ca6f70eb7c82b67966bd7c5c8eda08bd43488ac00000000","locktime":0,"size":225,"time":1629428623,"txid":"bd6e199de414844caccef1df421c7e9387f9084cb5a7e5e3922fc0a0750712a9","version":1,"vin":[{"scriptSig":{"asm":"304402203b8133fe6a0042b7491f7eb9a57107dbe575b5f88f5b907d0ad5761fde71a734022046073549710c5a71ddc63349a9814e9bf92aa16a5e8ec06d8a04ac06bc0b9220[ALL|FORKID] 030e5d88770c33a3ede650077c3b06461fdd56171caf86b2a23ce5cf3862bab3e1","hex":"47304402203b8133fe6a0042b7491f7eb9a57107dbe575b5f88f5b907d0ad5761fde71a734022046073549710c5a71ddc63349a9814e9bf92aa16a5e8ec06d8a04ac06bc0b92204121030e5d88770c33a3ede650077c3b06461fdd56171caf86b2a23ce5cf3862bab3e1"},"sequence":4294967294,"txid":"d12a5409dfa89a8c4594bff0d971064e2428a1bc325aac5ab2e14de260bea3f5","vout":1}],"vout":[{"n":0,"scriptPubKey":{"addresses":["bitcoincash:qz8ar37sd4a54hxxv6zkjdkf064sd7h7mv4t37cr4w"],"asm":"OP_DUP OP_HASH160 8fd1c7d06d7b4adcc666856936c97eab06fafedb OP_EQUALVERIFY OP_CHECKSIG","hex":"76a9148fd1c7d06d7b4adcc666856936c97eab06fafedb88ac","reqSigs":1,"type":"pubkeyhash"},"value":0.001},{"n":1,"scriptPubKey":{"addresses":["bitcoincash:qr7l2r9x7u8t0jptv7txh479erk6pz75xs5aj3wvdd"],"asm":"OP_DUP OP_HASH160 fdf50ca6f70eb7c82b67966bd7c5c8eda08bd434 OP_EQUALVERIFY OP_CHECKSIG","hex":"76a914fdf50ca6f70eb7c82b67966bd7c5c8eda08bd43488ac","reqSigs":1,"type":"pubkeyhash"},"value":0.00199548}]}}

</details>

I notice that there is no information about the transaction fee. Shouldn't this information be included?

**Comment by christroutner** [comment]
The miner fee is implicitly included in the transaction. This is part of the original Bitcoin protocol and our software has no control over it. I suggest reading Mastering Bitcoin Cash to learn more:

http://zh.thedev.id/mastering-bitcoin-cash/
