### ISSUE TITLE
v4 Wishlist

### ISSUE THREAD

**Issue by christroutner** [Permissionless-Software-Foundation/bch-api#70]
bch-api routes have a `/v3/` prefix, which is the current stable release. It's time to start thinking about breaking changes for a `/v4/` route. This Issue will capture ideas that could be changed in v4.

Add comments to this Issue for new items. The Summary below will periodically be updated to reflect these ideas.

## Summary
- `isValid` should be changed to `isValidSlp` on the various /slp/ route validation calls. Each call should return the same format, regardless of the source of the validation.

**Comment by christroutner** [comment]
v4 has already been deployed, but the wish above was not incorporated.

**Comment by SuperCipher** [comment]
Is there a place where I can see a list of breaking changes api?

**Comment by christroutner** [comment]
@SuperCipher we use Semantic Release, so the changes between CD releases is documented in each release:
https://github.com/Permissionless-Software-Foundation/bch-api/releases

We don't have a comprehensive list between major versions, because we have a CI/CD workflow that is constantly changing features.
