### ISSUE TITLE
run bch-api without enable middleware rate limit

### ISSUE THREAD

**Issue by SuperCipher** [Permissionless-Software-Foundation/bch-api#95]
@christroutner 
As a developer I want to run bch-api locally connect to regtest node I create without having to setup rate limit
implementation sample
https://github.com/ActorForth/bch-api/commit/eb42a0e0db2e4e6329daaf38a5a9dc636e9421ef#diff-c72a907ac323cd2f334ed0e2bd07d15ab62581c4753660c8a0d1c681b30be4b6R97

**Comment by christroutner** [comment]
If you don't want to comment out the rate-limit code directly, you can set the rate limits really high in the shell script used to start bch-api. Here are the settings in the example shell script:

https://github.com/Permissionless-Software-Foundation/bch-api/blob/master/start-dev-example.sh#L51-L56

Set these numbers to a big number, like 2000

**Comment by christroutner** [comment]
It could also be done with a new environment variable and an if-statement like you show in your code snippet.

I'm curious if setting the rate limits really high would work well though. As those environment variables already exist.

**Comment by SuperCipher** [comment]
> It could also be done with a new environment variable and an if-statement like you show in your code snippet.
> 
> I'm curious if setting the rate limits really high would work well though. As those environment variables already exist.

 Thank you @christroutner 
That would work too. But that would require running a Redis instance. With this particular use case, to run local API for local testing, it's seems inefficient to have another container of Redis running locally without serve it's purpose.

**Comment by christroutner** [comment]
This feature implemented in #112. Rate limits can be turned off by setting the `DO_NOT_USE_RATE_LIMITS` environment variable.
